### ISSUE TITLE
Operator for Bucket, Users, policies, etc

### ISSUE THREAD

**Issue by bclermont** [minio/minio-operator#68]
This is not an issue. I couldn't find a good channel to communicate with this project.

As this operator focus on the cluster itself, I created an other operator that take care of users, buckets and their policy.

https://github.com/robotinfra/minio-resources-operator

Should these features be into this operator?

**Comment by nitisht** [comment]
@bclermont thank you for reaching out. Yes, IMO this would a great addition to our operator. Please feel free to send a PR

**Comment by harshavardhana** [comment]
The plan is to do this under https://github.com/minio/m3 which does this already to some extent.

Feel free to open issues there, the scope of this operator is limited to deployment simplicity only.

**Comment by jabbors** [comment]
I'd be very interested to see these features integrated into this operator. 

Instead of supporting it in some other project like https://github.com/minio/console, which replaces the now archived https://github.com/minio/m3 project, I strongly believe the operator shall manage the entire life cycle.

I'm willing to send you a PR if @bclermont doesn't have time.

**Comment by mitchellmaler** [comment]
@nitisht @harshavardhana Since m3 is archived and has been replaced with console do you expect console be where this capability should exist or is that out of scope for that project?

**Comment by harshavardhana** [comment]
> @nitisht @harshavardhana Since m3 is archived and has been replaced with console do you expect console be where this capability should exist or is that out of scope for that project?

Most functionality will be in console, operator is just headless here with just APIs so feel free to move it there.
